install library

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.8 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

import library

In [3]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [12]:
#scrape all available reviews
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.spotify.music',
    lang = 'id',
    country = 'id',
    sort = Sort.NEWEST,
    count=10000,
    filter_score_with=None
)

show data yang sudah di crawling

In [13]:
#df_busu = busu itu variabel jadi bisa di ketik apa saja
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,7667c2b6-59f6-4727-880c-a70e4b97208d,A. Kyy,https://play-lh.googleusercontent.com/a-/ALV-U...,"kikir, banyak iklan. denger lagu cuma 1 - 2 la...",1,1,9.1.36.1948,2026-04-12 15:36:55,Hai. Kami sangat menghargai masukan Anda. Kami...,2026-03-19 12:24:35,9.1.36.1948
9996,02d27fbc-f2c8-4551-95f7-bfac7ad7bd21,Maulidya Yumna,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus sekali aplikasi ini,5,0,9.1.36.1948,2026-04-12 15:34:18,None,NaT,9.1.36.1948
9997,90b1720e-5602-4678-ab61-09deb95801b1,Fariha Fariha,https://play-lh.googleusercontent.com/a-/ALV-U...,"baguss polll apk ne,tapi ne ojo ana aken biaya ya",5,0,9.1.36.1948,2026-04-12 15:10:07,None,NaT,9.1.36.1948
9998,a944ec1e-61fc-4dfc-a9ac-01db511a4a48,ryzztzyy fhritzyy,https://play-lh.googleusercontent.com/a/ACg8oc...,"keren,lebih keren lagi jika bisa mendownload v...",3,0,None,2026-04-12 15:03:35,None,NaT,None
9999,26d25c59-ffe0-4af7-a722-6c1fc7d14feb,Su Kesi,https://play-lh.googleusercontent.com/a-/ALV-U...,gak suka terlalu banyak iklan 🙏,4,0,9.1.36.1948,2026-04-12 15:01:35,Kami mendengarnya dan kami akan meneruskan ump...,2026-04-12 20:43:28,9.1.36.1948

ambil data yang dibutuhkan

In [14]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,A. Kyy,1,2026-04-12 15:36:55,"kikir, banyak iklan. denger lagu cuma 1 - 2 la..."
9996,Maulidya Yumna,5,2026-04-12 15:34:18,bagus sekali aplikasi ini
9997,Fariha Fariha,5,2026-04-12 15:10:07,"baguss polll apk ne,tapi ne ojo ana aken biaya ya"
9998,ryzztzyy fhritzyy,3,2026-04-12 15:03:35,"keren,lebih keren lagi jika bisa mendownload v..."
9999,Su Kesi,4,2026-04-12 15:01:35,gak suka terlalu banyak iklan 🙏

In [15]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [17]:
#simpan dataset ke dalam file
my_df.to_csv("DataSetSpotify.csv", index = False)