<a href="https://colab.research.google.com/github/Mldyalaura/spotify/blob/main/Label_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
#untuk omputasi numerik
import numpy as pd

#memproses pengelolaan text
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola kata spesfik yang dicari
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

**New Section**

In [ ]:
#import library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [ ]:
df = pd.read_csv('/content/DataSetSpotify.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,5,2026-06-01 04:08:46,bagussss bangettt
1,Pengguna Google,5,2026-06-01 04:03:05,dengerin lagu lebih gampang apk nya
2,Pengguna Google,5,2026-06-01 03:55:57,bagus
3,Pengguna Google,5,2026-06-01 03:42:36,sangat bagus
4,Pengguna Google,1,2026-06-01 03:34:49,terlalu banyak iklan

In [ ]:
df['sentiment'] = df['score'].map({1.0:0, 2.0:0, 3.0:1, 4.0:1, 5.0:1})

In [ ]:
#ambil teks aja untuk kita labelkan
dataku = pd.DataFrame(df[['content','sentiment']])
dataku.head(10)

,content,sentiment
0,bagussss bangettt,1
1,dengerin lagu lebih gampang apk nya,1
2,bagus,1
3,sangat bagus,1
4,terlalu banyak iklan,0
5,aplikasi yahudi full iklan Cok dikit dikit iklan,1
6,"anjr apk kikir kebelet haji, iklan banyak bet juanco prasaan dlu kagak etdah buset. udh mah boikot, jirlah. itaiyo itaiyo",0
7,bagus lagu nya juga enak di dengar tapi KENAPA GABISA DI ULANG OI KENAPAAAAAAA,1
8,"kikir, mau pilih lagu aja disuruh bayar",0
9,bgus,1

In [ ]:
my_df = dataku[['content', 'sentiment']]

In [ ]:
#simpen dataset ke dalam file
my_df.to_csv("label_spotify.csv", index = False)